# Generated by Django 2.0.5 on 2018-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.FloatField()),
                ('numbersSold', models.IntegerField()),
            ],
        ),
    ]
