# Generated by Django 2.0.5 on 2018-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numbersSold',
            field=models.IntegerField(default=0),
        ),
    ]
