# Generated by Django 2.0.5 on 2018-05-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0002_auto_20180520_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(default=500)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='belongsTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kontrollsystemApp.Cafe'),
        ),
    ]
