# Generated by Django 2.0.5 on 2018-05-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0003_auto_20180522_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='belongsTo',
        ),
        migrations.DeleteModel(
            name='Cafe',
        ),
    ]
