# Generated by Django 2.0.5 on 2018-05-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0004_auto_20180522_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrollsystemApp.Product')),
            ],
        ),
    ]
