# Generated by Django 2.0.5 on 2018-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0006_auto_20180523_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('mat', 'Matrett'), ('drikke', 'Drikke')], default=('mat', 'Matrett'), max_length=64),
        ),
    ]
