# Generated by Django 2.0.5 on 2018-05-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0007_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='belongsTo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kontrollsystemApp.Cafe'),
        ),
    ]
