# Generated by Django 2.0.5 on 2018-05-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontrollsystemApp', '0008_auto_20180524_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
